import 'package:app/model/broker.dart';
import 'package:app/model/category.dart';

// Categories
// const DUMMY_CATEGORIES = const [
//   Category(
//     id: 0,
//     name: "All",
//   ),
//   Category(
//     id: 1,
//     name: "Business",
//   ),
//   Category(
//     id: 2,
//     name: "Commodity",
//   ),
//   Category(
//     id: 3,
//     name: "Customer",
//   ),
//   Category(
//     id: 4,
//     name: "Information",
//   ),
//   Category(
//     id: 5,
//     name: "Intellectual",
//   ),
//   Category(
//     id: 6,
//     name: "Real estate",
//   ),
//   Category(
//     id: 7,
//     name: "Sponsorship",
//   ),
//   Category(
//     id: 8,
//     name: "Stock",
//   ),
//   Category(
//     id: 9,
//     name: "office",
//   ),
//   Category(
//     id: 10,
//     name: "Service",
//   ),
//   Category(
//     id: 11,
//     name: "Insurance",
//   ),
//   Category(
//     id: 12,
//     name: "Discount",
//   ),
//   Category(
//     id: 13,
//     name: "Credit",
//   ),
//   Category(
//     id: 14,
//     name: "Leasing",
//   ),
// ];
// Brokers
List<Broker> DUMMY_BROKERS = [
  Broker(
      id: 0,
      name: "Ato Balcha",
      categoryId: 9,
      image: 'assets/images/16.jpg',
      rating: 4.0,
      view: 8.7,
      about: "My name is Ato balcha a hose broker",
      completedWorks: 40.5,
      workInProgress: 30.5,
      communicationSkill: 60.9,
      brokingSkill: 70.0,
      isFavorite: false),
  Broker(
      id: 1,
      name: "Yohanes Abebaw",
      categoryId: 1,
      image:  'assets/images/16.jpg',
      rating: 4.0,
      view: 8.7,
      about: "My name is yohanes abebaw and I am a commodity broker expoert",
      completedWorks: 20.5,
      workInProgress: 40.5,
      communicationSkill: 80.9,
      brokingSkill: 80.0,
      isFavorite: false),
  Broker(
      id: 2,
      name: "Ato Telahun",
      categoryId: 2,
      image:  'assets/images/16.jpg',
      rating: 4.6,
      view: 5.7,
      about: "My name is Ato Telahun I am customer broker expert",
      completedWorks: 50.0,
      workInProgress: 30.5,
      communicationSkill: 90.0,
      brokingSkill: 80.0,
      isFavorite: false),
  Broker(
      id: 3,
      name: "Mishan Assefa",
      categoryId: 3,
      image: 'assets/images/16.jpg',
      rating: 4.5,
      view: 9.7,
      about: "My name is mishan assefa I am an information broker expert",
      completedWorks: 40.5,
      workInProgress: 30.5,
      communicationSkill: 80.9,
      brokingSkill: 60.0,
      isFavorite: false),
  Broker(
      id: 4,
      name: "Ato Gugsa",
      categoryId: 4,
      image:  'assets/images/16.jpg',
      rating: 3.0,
      view: 7.7,
      about: "My name is Ato gugsa I am a business broker expert",
      completedWorks: 50.5,
      workInProgress: 50.5,
      communicationSkill: 80.9,
      brokingSkill: 80.0,
      isFavorite: false),
  Broker(
      id: 5,
      name: "Daniela Yilma",
      categoryId: 5,
      image:  'assets/images/16.jpg',
      rating: 4.6,
      view: 7.7,
      about: "My name is daniela yilma and I am an intelectual broking expert",
      completedWorks: 80.5,
      workInProgress: 30.5,
      communicationSkill: 80.9,
      brokingSkill: 90.0,
      isFavorite: false),
  Broker(
      id: 6,
      name: "Ato Balcha",
      categoryId: 6,
      image: 'assets/images/16.jpg',
      rating: 4.0,
      view: 8.7,
      about: "My name is Ato balcha a hose broker",
      completedWorks: 40.5,
      workInProgress: 30.5,
      communicationSkill: 60.9,
      brokingSkill: 70.0,
      isFavorite: false),
  Broker(
      id: 7,
      name: "Merry Girma",
      categoryId: 7,
      image: 'assets/images/16.jpg',
      rating: 5.0,
      view: 9.7,
      about: "My name is Merry Girma a Real state broking expert",
      completedWorks: 30.5,
      workInProgress: 40.5,
      communicationSkill: 70.9,
      brokingSkill: 80.0,
      isFavorite: false),
  Broker(
      id: 8,
      name: "Abel Freayehu",
      categoryId: 8,
      image:  'assets/images/16.jpg',
      rating: 4.0,
      view: 8.7,
      about: "My name is Ato balcha a hose broker",
      completedWorks: 40.5,
      workInProgress: 30.5,
      communicationSkill: 60.9,
      brokingSkill: 70.0,
      isFavorite: false),
];
